modLoader="javafml" #mandatory
loaderVersion="[35.1,36.9]" #mandatory
license="GNU General Public License version 3 (GPLv3)"
issueTrackerURL="https://github.com/Alex-MacLean/TheLegendOfHerobrine/issues" #optional
[[mods]] #mandatory
modId = "herobrine" #mandatory
version = "0.6.3-RC4" #mandatory
displayName = "The Legend of Herobrine" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/Alex-MacLean/TheLegendOfHerobrine/master/update.json" #optional
displayURL = "https://www.herobrinemod.com" #optional
logoFile = "Logo.png" #optional
credits = '''Russian Translation - KickDemonAss,
Polish Translation - kubix1006, 
Chinese Translation - rtxyd,
Spanish Translation - Dewinn12,
Optimization - guliver-jham''' #optional
authors = "Alex MacLean" #optional
description='''
Adds Herobrine to Minecraft, and other herobrine related things.
'''
[[dependencies.herobrine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1,36.9]" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.herobrine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"