modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/Alex-MacLean/TheLegendOfHerobrine/issues" #optional
[[mods]] #mandatory
modId="herobrine" #mandatory
version="0.3.2" #mandatory
displayName="The Legend of Herobrine" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Alex-MacLean/TheLegendOfHerobrine/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-legend-of-herobrine" #optional
logoFile="Logo.png" #optional
credits="Alex MacLean" #optional
authors="Alex MacLean" #optional
description='''
Adds Herobrine to Minecraft, and other herobrine related things
'''
[[dependencies.herobrine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.herobrine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"